version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: typescript
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: build
      scope: node
      include: scope
