#!/usr/bin/env bash

# Set strict mode for bash
set -euo pipefail

# Bright ANSI color escape sequences.
BRIGHT_MAGENTA=$'\e[1;35m'
BRIGHT_CYAN=$'\e[1;36m'

# Reset all ANSI attributes.
NO_COLOR=$'\e[0m'

# Named colors
MESSAGE_COLOR="${BRIGHT_CYAN}"
VALUE_COLOR="${BRIGHT_MAGENTA}"

#######################################################################################################################
# Pre-commit hook script
#######################################################################################################################

echo "${MESSAGE_COLOR}[pre-commit] Running pre-commit script...${NO_COLOR}"
set -x
npm run husky:pre-commit
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}[pre-commit] Removing dev dependencies from the local ${VALUE_COLOR}node_modules/${MESSAGE_COLOR} folder...${NO_COLOR}"
set -x
npm install --omit=dev
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}[pre-commit] Force adding the ${VALUE_COLOR}node_modules/${MESSAGE_COLOR} folder to the commit...${NO_COLOR}"
set -x
git add -f -A node_modules/
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}[pre-commit] Excluding work dirs from the commit...${NO_COLOR}"
echo "git rm --cached -r node_modules/.bin/ 2>/dev/null"
git rm --cached -r node_modules/.bin/ 2>/dev/null || true
echo "git rm --cached node_modules/.package-lock.json"
git rm --cached  node_modules/.package-lock.json 2>/dev/null || true
echo "git rm --cached -r node_modules/.vite/ 2>/dev/null"
git rm --cached -r node_modules/.vite/ 2>/dev/null || true
echo "git rm --cached -r node_modules/.vite-temp/ 2>/dev/null"
git rm --cached -r node_modules/.vite-temp/ 2>/dev/null || true
echo

echo "${MESSAGE_COLOR}[pre-commit] Git status after the changes...${NO_COLOR}"
set -x
git status
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}Committing the changes...${NO_COLOR}"
echo
